### PR TITLE
Enable rhel-7-server-optional-rpms repo

### PR DESCRIPTION
**Pull request by arajkumar**
This PR is based on the discussion from https://github.com/rhdt/EL-Dockerfiles/pull/83.

### CODE REVIEW

**Comment by arajkumar** [comment]
@jmelis PTAL. Thanks.

**Comment by jmelis** [comment]
[test]

**Comment by jmelis** [comment]
@arajkumar @lucky-suman it seems like EPEL and RHEL7 changed the pithon3 packages, so now most builds that were working before are failing. I'm trying to fix this in https://github.com/rhdt/EL-Dockerfiles/pull/88

As soon as I have it ready I will ask you to rebase.

In any case I would appreciate help if you could help me get the builds working again. The builds that are failing are the analytics ones.

**Comment by arajkumar** [comment]
@jmelis I will give a try for sure :) BTW, is this broken due to recent RHEL update(7.7)? 

IMHO we should consider referring the base image with a tag. Instead of `registry.access.redhat.com/rhel7` we should use `registry.access.redhat.com/rhel7:7.6`.

**Comment by jmelis** [comment]
> IMHO we should consider referring the base image with a tag. Instead of registry.access.redhat.com/rhel7 we should use registry.access.redhat.com/rhel7:7.6.

+1

**Comment by arajkumar** [comment]
It will be taken care as part of #89.

**Pull request closed without merging**
