### PR TITLE
Install new mercator package

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Related to https://github.com/fabric8-analytics/fabric8-analytics-server/pull/427.

**Comment by msrb** [comment]
@jmelis @riuvshin PTAL guys, thanks :)

**Comment by riuvshin** [comment]
[test]

**Comment by msrb** [comment]
Hmm, weird error:

```
--> Processing Dependency: pcp-libs = 4.1.0-0.201805281909.git68ab4b18.el7 for package: pcp-pmda-prometheus-4.1.0-0.201805281909.git68ab4b18.el7.x86_64
--> Finished Dependency Resolution
Error: Package: pcp-pmda-prometheus-4.1.0-0.201805281909.git68ab4b18.el7.x86_64 (fche-pcp)
           Requires: pcp-libs = 4.1.0-0.201805281909.git68ab4b18.el7
           Available: pcp-libs-3.8.10-8.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.8.10-8.el7
           Available: pcp-libs-3.9.10-8.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.9.10-8.el7
           Available: pcp-libs-3.10.6-2.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.10.6-2.el7
           Available: pcp-libs-3.11.3-4.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.11.3-4.el7
           Available: pcp-libs-3.11.8-7.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.11.8-7.el7
           Available: pcp-libs-3.12.2-5.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 3.12.2-5.el7
           Available: pcp-libs-4.1.0-0.201805281909.git68ab4b18.el7.x86_64 (fche-pcp)
               pcp-libs = 4.1.0-0.201805281909.git68ab4b18.el7
           Available: pcp-libs-4.1.0-4.el7.i686 (rhel-7-server-rpms)
               pcp-libs = 4.1.0-4.el7
           Available: pcp-libs-4.1.0-5.el7_6.i686 (rhel-7-server-rpms)
               pcp-libs = 4.1.0-5.el7_6
```

@fche any idea about the error above? It looks like https://github.com/rhdt/EL-Dockerfiles/tree/master/base/golang is failing to build from some reason (https://zabbix.devshift.net:9444/job/rhel-golang-master/).

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
@msrb there is another problem now PTAL latest logs

**Comment by fche** [comment]
I gather the pcp-related build error was temporary?  (In any case, a newer build ought to take their place after today.)

**Comment by riuvshin** [comment]
[test]

**Comment by msrb** [comment]
Rebased, let's see now :)

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
works now :)

**Comment by msrb** [comment]
:man_dancing: 

:)

**Pull request merged**
