### PR TITLE
Add Python3-dev for updating dependencies requirements

### PR DESCRIPTION
**Pull request by lucky-suman**
Adding python3-dev, so that Cython and other python packages requirements get satisfied.

### CODE REVIEW

**Comment by aditya-konarde** [comment]
[test]

**Review by jmelis — CHANGES_REQUESTED** [review]
it doesn't look like that package exists:

```
$ docker run --rm -it registry.access.redhat.com/rhel7
[root@6302b19def83 /]# yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Examining /var/tmp/yum-root-_9fTas/epel-release-latest-7.noarch.rpm: epel-release-7-12.noarch
Marking /var/tmp/yum-root-_9fTas/epel-release-latest-7.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-12 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================================================================================
 Package                                                Arch                                             Version                                          Repository                                                               Size
========================================================================================================================================================================================================================================
Installing:
 epel-release                                           noarch                                           7-12                                             /epel-release-latest-7.noarch                                            24 k

Transaction Summary
========================================================================================================================================================================================================================================
Install  1 Package

Total size: 24 k
Installed size: 24 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : epel-release-7-12.noarch                                                                                                                                                                                             1/1 
  Verifying  : epel-release-7-12.noarch                                                                                                                                                                                             1/1 

Installed:
  epel-release.noarch 0:7-12                                                                                                                                                                                                            

Complete!
[root@6302b19def83 /]# yum install python3-dev
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
epel/x86_64/metalink                                                                                                                                                                                             |  25 kB  00:00:00     
epel                                                                                                                                                                                                             | 5.4 kB  00:00:00     
(1/3): epel/x86_64/group_gz                                                                                                                                                                                      |  90 kB  00:00:00     
(2/3): epel/x86_64/updateinfo                                                                                                                                                                                    | 1.0 MB  00:00:00     
(3/3): epel/x86_64/primary_db                                                                                                                                                                                    | 6.9 MB  00:00:01     
No package python3-dev available.
Error: Nothing to do
```

**Comment by arajkumar** [comment]
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm doesn't seem to have python36-devel. It seem to be available with `rhel-7-server-optional-rpms` repo.
Adding `subscription-manager repos --enable rhel-7-server-optional-rpms` worked in my local docker setup.

```
docker run -it registry.access.redhat.com/rhel7
subscription-manager register #register with RedHat account
subscription-manager attach
subscription-manager repos --enable rhel-7-server-optional-rpms
yum install -y python3-devel
```

**Comment by jmelis** [comment]
@arajkumar please add the following to your Dockerfile:

```yum-config-manager --enable rhel-7-server-optional-rpms```

example here: https://github.com/rhdt/EL-Dockerfiles/blob/master/base/fabric8-analytics-jobs/Dockerfile#L3

**Comment by arajkumar** [comment]
@jmelis. Thanks for the information. I can do that.

**Pull request closed without merging**
