### PR TITLE
Fix build issues related to fabric8-analytics base images

### PR DESCRIPTION
**Pull request by arajkumar**
… (#82)"

This reverts commit f58715c96a3f4782c064e75ddada81d364e6f19b.

### CODE REVIEW

**Comment by jmelis** [comment]
[test]

**Comment by arajkumar** [comment]
[test]

**Comment by arajkumar** [comment]
@jmelis , looks like I don't have the rights to trigger the PR check.

**Comment by jmelis** [comment]
[test]

**Comment by jmelis** [comment]
[test]

**Comment by arajkumar** [comment]
[test]

**Comment by jmelis** [comment]
[test]

**Comment by jmelis** [comment]
[test]

**Pull request merged**
